"""
Native Python implementation of the CycleRAP scoring algorithm (CycleRAP v2.14).

Updated 2026-07-08 to match the supplier reference workbook
`CycleRAP - model - generation v2.14-to supliers.xlsm` ("CycleRAP Model" tab).
All factor tables are loaded from `data/cyclerap_v214_model.json`, which is
generated by `scripts/extract_v214_model.py` — do not edit the tables by hand;
re-run the extractor against the workbook instead.

Key v2.14 semantics implemented here:
  - Road-speed risk factor is a per-integer-speed lookup table (0-150 with
    separate km/h and mph columns), replacing the v2.13 sigmoid.
  - Risk-band thresholds are INCLUSIVE upper bounds (BB/BP/SB: <=5 Low,
    <=10 Medium, <=20 High; VB: <=10/<=25/<=60), matching BU4/BU9/BU18/BU29.
  - CU52: the Delineation factor inside the vehicle-impact chain (CM42) is 1.2
    only when Delineation is Present AND Adjacent vehicle parking 0-1m is
    Present (`=IF(AND(CT52=1,CT45=1),1.2,1)`), independent of the delineation
    lookup-table factor used in CM3.
  - The 'Unaccessible facility - Part 2' trigger (CQ46) evaluates in the
    workbook to the facility's own category (the OFFSET column MATCH always
    self-matches), so it reduces to the facility-type VB-conditional column
    (DR) — verified against cached workbook values.

No Windows, Excel, or VBA macros required - pure Python implementation.
"""

import json
from pathlib import Path

import pandas as pd
import numpy as np
from app.services.serializer import Attributes


# ============ MODEL DATA (extracted from the v2.14 workbook) ============
_MODEL_JSON = Path(__file__).resolve().parent / "data" / "cyclerap_v214_model.json"
with open(_MODEL_JSON, "r", encoding="utf-8") as _f:
    _MODEL = json.load(_f)

MODEL_VERSION = _MODEL["version"]

# Risk multiplier + conditional trigger flag per attribute option.
# Same shape as the historical hardcoded dict: {attr_key: {cat: {'risk','cond'}}}
LOOKUP_TABLES = {
    attr: {int(cat): entry for cat, entry in opts.items()}
    for attr, opts in _MODEL["lookup_tables"].items()
}
# facility_type carries extra columns from DN3:DT8 (bp_cond/vb_cond/vb_sev/vb_cf)
LOOKUP_TABLES["facility_type"] = {
    int(cat): {
        "risk": 1.0,
        "cond": entry["vb_cond"],
        "bp_cond": entry["bp_cond"],
        "vb_cond": entry["vb_cond"],
        "vb_sev": entry["vb_sev"],
        "vb_cf": entry["vb_cf"],
    }
    for cat, entry in _MODEL["facility_type"].items()
}

# ============ BACKEND FIELD NAME CONSTANTS ============
# Use field names directly from Attributes.Fields for consistency
FACILITY_TYPE = Attributes.Fields.FACILITY_TYPE_STR
FACILITY_ACCESS = Attributes.Fields.FACILITY_ACCESS_STR
LOOSE_SURFACE = Attributes.Fields.LOOSE_SLIPPERY_SURFACE_STR
TRAM_RAILS = Attributes.Fields.TRAM_TRAIN_RAIL_STR
SURFACE_DEFORMATION = Attributes.Fields.DEFORMATION_DRAIN_STR
FIXED_OBSTACLE = Attributes.Fields.FIXED_OBSTACLE_STR
NON_FIXED_OBSTACLE = Attributes.Fields.NON_FIXED_OBSTACLE_STR
DELINEATION = Attributes.Fields.DELINEATION_STR
LIGHT_SEGREGATION = Attributes.Fields.LIGHT_SEGREGATION_STR
FACILITY_WIDTH = Attributes.Fields.FACILITY_WIDTH_STR
FLOW_DIRECTION = Attributes.Fields.FLOW_DIR_STR
WIDTH_RESTRICTION = Attributes.Fields.WIDTH_RESTRICTION_STR
ADJACENT_ROAD_0_1M = Attributes.Fields.ADJ_ROAD_LANE_01M_STR
ADJACENT_PARKING_0_1M = Attributes.Fields.ADJ_VHCL_PARKING_01M_STR
ADJACENT_HAZARD_0_1M = Attributes.Fields.ADJ_SVR_PARKING_01M_STR
ADJACENT_OBJECT_0_1M = Attributes.Fields.ADJ_OBJ_LVL_CHGE_01M_STR
ADJACENT_SIDEWALK_0_1M = Attributes.Fields.ADJ_SIDEWALK_01M_STR
ADJACENT_ROAD_1_3M = Attributes.Fields.ADJ_ROAD_LANE_13M_STR
ADJACENT_PARKING_1_3M = Attributes.Fields.ADJ_VHCL_PARKING_13M_STR
ADJACENT_HAZARD_1_3M = Attributes.Fields.ADJ_SVR_HAZARD_13M_STR
ADJACENT_OBJECT_1_3M = Attributes.Fields.ADJ_OBJ_LVL_CHGE_13M_STR
ADJACENT_SIDEWALK_1_3M = Attributes.Fields.ADJ_SIDEWALK_13M_STR
GRADE = Attributes.Fields.GRADE_STR
CURVATURE = Attributes.Fields.CURV_STR
STREET_LIGHTING = Attributes.Fields.STREET_LIGHT_STR
PEDESTRIAN_CROSSING = Attributes.Fields.PED_CROSS_STR
INTERSECTING_FACILITY = Attributes.Fields.INTERSECT_FACILITY_STR
INTERSECTION_APPROACH = Attributes.Fields.INTERSECT_APPRCH_STR
INTERSECTION_CROSSING = Attributes.Fields.INTERSECT_ROAD_CROSS_STR
CROSSING_FACILITY = Attributes.Fields.CROSS_FACILITY_STR
NUM_LANES_ADJACENT = Attributes.Fields.NOL_ADJ_ROAD_STR
NUM_LANES_INTERSECTING = Attributes.Fields.NOL_INTERSECT_ROAD_STR
PROPERTY_ACCESS = Attributes.Fields.PROP_ACCESS_STR
PEDESTRIAN_FLOW = Attributes.Fields.PEAK_PED_FLOW_STR
BICYCLE_FLOW = Attributes.Fields.PEAK_BICYCLE_TRAFFIC_FLOW_STR
CARGO_BIKES = Attributes.Fields.OBSERVED_PROPORTION_STR
BICYCLE_SPEED = Attributes.Fields.BICYCLE_SPD_AVG_STR
SPEED_DIFFERENTIAL = Attributes.Fields.BICYCLE_SPD_DIFF_STR
ROAD_AADT = Attributes.Fields.ROAD_AADT_STR
HEAVY_VEHICLE = Attributes.Fields.HEAVY_VHCL_FLOW_STR
ROAD_SPEED = Attributes.Fields.ROAD_OPR_SPEED_AVG_STR
SPEED_UNIT = Attributes.Fields.SPEED_UNIT_STR
LINE_OF_SIGHT = Attributes.Fields.LINE_OF_SIGHT_STR


# Module lookup key -> backend attributes.csv column (for baseline generation)
_MODULE_KEY_TO_FIELD = {
    "facility_access": FACILITY_ACCESS,
    "loose_surface": LOOSE_SURFACE,
    "tram_rails": TRAM_RAILS,
    "surface_deformation": SURFACE_DEFORMATION,
    "fixed_obstacle": FIXED_OBSTACLE,
    "non_fixed_obstacle": NON_FIXED_OBSTACLE,
    "delineation": DELINEATION,
    "light_segregation": LIGHT_SEGREGATION,
    "line_of_sight": LINE_OF_SIGHT,
    "facility_width": FACILITY_WIDTH,
    "flow_direction": FLOW_DIRECTION,
    "width_restriction": WIDTH_RESTRICTION,
    "adjacent_road_0_1m": ADJACENT_ROAD_0_1M,
    "adjacent_parking_0_1m": ADJACENT_PARKING_0_1M,
    "adjacent_hazard_0_1m": ADJACENT_HAZARD_0_1M,
    "adjacent_object_0_1m": ADJACENT_OBJECT_0_1M,
    "adjacent_sidewalk_0_1m": ADJACENT_SIDEWALK_0_1M,
    "adjacent_road_1_3m": ADJACENT_ROAD_1_3M,
    "adjacent_parking_1_3m": ADJACENT_PARKING_1_3M,
    "adjacent_hazard_1_3m": ADJACENT_HAZARD_1_3M,
    "adjacent_object_1_3m": ADJACENT_OBJECT_1_3M,
    "adjacent_sidewalk_1_3m": ADJACENT_SIDEWALK_1_3M,
    "grade": GRADE,
    "curvature": CURVATURE,
    "street_lighting": STREET_LIGHTING,
    "pedestrian_crossing": PEDESTRIAN_CROSSING,
    "intersecting_facility": INTERSECTING_FACILITY,
    "intersection_approach": INTERSECTION_APPROACH,
    "intersection_crossing": INTERSECTION_CROSSING,
    "crossing_facility": CROSSING_FACILITY,
    "num_lanes_adjacent": NUM_LANES_ADJACENT,
    "num_lanes_intersecting": NUM_LANES_INTERSECTING,
    "property_access": PROPERTY_ACCESS,
    "pedestrian_flow": PEDESTRIAN_FLOW,
    "bicycle_flow": BICYCLE_FLOW,
    "cargo_bikes": CARGO_BIKES,
    "bicycle_speed": BICYCLE_SPEED,
    "speed_differential": SPEED_DIFFERENTIAL,
    "heavy_vehicle": HEAVY_VEHICLE,
}

# Safest coded option per attribute (drives the top-contributor analysis).
# Generated from the workbook factor tables; facility type is pinned to 3
# (off-road bicycle path) and the numeric attributes keep their historical
# safest values.
BASELINE_VALUES = {
    _MODULE_KEY_TO_FIELD[key]: int(cat)
    for key, cat in _MODEL["baselines"].items()
    if key in _MODULE_KEY_TO_FIELD
}
BASELINE_VALUES[FACILITY_TYPE] = 3
BASELINE_VALUES[ROAD_AADT] = 0
BASELINE_VALUES[ROAD_SPEED] = 1


def get_risk(attr_key: str, value: int) -> float:
    """Get risk factor from lookup table"""
    return LOOKUP_TABLES.get(attr_key, {}).get(value, {}).get('risk', 1.0)


def get_cond(attr_key: str, value: int) -> int:
    """Get condition flag from lookup table"""
    return LOOKUP_TABLES.get(attr_key, {}).get(value, {}).get('cond', 0)


# ============ AADT LOOKUP TABLE ============
# v2.14 DI3:DK19 exact values (0.25 .. 2.2522, +7% compounding above 2500).
AADT_LOOKUP_TABLE = [
    {"threshold": entry["threshold"], "risk": entry["risk"]}
    for entry in _MODEL["aadt_table"]
]


def get_aadt_risk_factor(aadt: float) -> float:
    """Calculate AADT risk factor from lookup table (VLOOKUP approximate
    match: highest threshold <= aadt)."""
    result = AADT_LOOKUP_TABLE[0]['risk']
    for entry in AADT_LOOKUP_TABLE:
        if aadt >= entry['threshold']:
            result = entry['risk']
        else:
            break
    return result


# ============ ROAD SPEED RISK TABLE ============
# v2.14 replaced the sigmoid with fixed per-integer-speed factors (DD93:DF243),
# indexed 0..150 with separate km/h and mph columns.
SPEED_RISK_TABLE = {
    "kmh": _MODEL["speed_table"]["kmh"],
    "mph": _MODEL["speed_table"]["mph"],
}


def get_road_speed_risk_factor(speed: float, unit: int = 1) -> float:
    """Road-speed risk factor — CycleRAP v2.14 lookup table.

    The workbook rounds the mean operating speed to the nearest integer
    (DE90 = ROUND(O58,0)) and looks it up exactly in the 0-150 table, with the
    column selected by the speed unit. `unit` follows
    Attributes.Fields.SPEED_UNIT_STR ({'km/h': 1, 'mph': 2}).
    Out-of-range speeds are clamped to the table bounds.
    """
    if speed is None:
        return 1.0
    try:
        speed = float(speed)
    except (TypeError, ValueError):
        return 1.0
    column = SPEED_RISK_TABLE["mph"] if int(unit or 1) == 2 else SPEED_RISK_TABLE["kmh"]
    # Excel ROUND: half away from zero
    idx = int(np.floor(speed + 0.5)) if speed >= 0 else 0
    idx = min(max(idx, 0), len(column) - 1)
    return column[idx]


# ============ CM FORMULA IMPLEMENTATIONS ============
def calculate_cm3(row: pd.Series) -> float:
    """CM3 'Avoidance manoeuvre' (CycleRAP Model CM3) — the only likelihood
    component without a zero-gate on its triggers."""
    cu_factors = [
        get_risk('loose_surface', row.get(LOOSE_SURFACE, 2)),
        get_risk('line_of_sight', row.get(LINE_OF_SIGHT, 1)),
        get_risk('delineation', row.get(DELINEATION, 2)),
        get_risk('facility_width', row.get(FACILITY_WIDTH, 3)),
        get_risk('flow_direction', row.get(FLOW_DIRECTION, 1)),
        get_risk('width_restriction', row.get(WIDTH_RESTRICTION, 2)),
        get_risk('grade', row.get(GRADE, 1)),
        get_risk('cargo_bikes', row.get(CARGO_BIKES, 1)),
        get_risk('pedestrian_flow', row.get(PEDESTRIAN_FLOW, 1)),
        get_risk('bicycle_flow', row.get(BICYCLE_FLOW, 1)),
        get_risk('speed_differential', row.get(SPEED_DIFFERENTIAL, 1)),
        get_risk('curvature', row.get(CURVATURE, 2)),
        get_risk('street_lighting', row.get(STREET_LIGHTING, 1)),
    ]

    cq_triggers = [
        get_cond('surface_deformation', row.get(SURFACE_DEFORMATION, 2)),
        get_cond('fixed_obstacle', row.get(FIXED_OBSTACLE, 2)),
        get_cond('non_fixed_obstacle', row.get(NON_FIXED_OBSTACLE, 2)),
        get_cond('adjacent_parking_0_1m', row.get(ADJACENT_PARKING_0_1M, 2)),
        get_cond('intersection_crossing', row.get(INTERSECTION_CROSSING, 2)),
        get_cond('property_access', row.get(PROPERTY_ACCESS, 2)),
        get_cond('intersecting_facility', row.get(INTERSECTING_FACILITY, 2)),
        get_cond('pedestrian_crossing', row.get(PEDESTRIAN_CROSSING, 2)),
    ]

    cu_product = np.prod(cu_factors)
    cq_sum = sum(cq_triggers)
    return cu_product ** (1 + cq_sum * 0.1)


def calculate_cm17(row: pd.Series) -> float:
    """CM17 'Loss of control – speed' (v2.13 name: CM16)."""
    cq17_triggers = [
        get_cond('loose_surface', row.get(LOOSE_SURFACE, 2)),
        get_cond('grade', row.get(GRADE, 1)),
        get_cond('curvature', row.get(CURVATURE, 2)),
    ]
    cq_sum = sum(cq17_triggers)
    if cq_sum == 0:
        return 0

    cu17_factors = [
        get_risk('intersection_crossing', row.get(INTERSECTION_CROSSING, 2)),
        get_risk('line_of_sight', row.get(LINE_OF_SIGHT, 1)),
        get_risk('property_access', row.get(PROPERTY_ACCESS, 2)),
        get_risk('intersecting_facility', row.get(INTERSECTING_FACILITY, 2)),
        get_risk('pedestrian_crossing', row.get(PEDESTRIAN_CROSSING, 2)),
        get_risk('facility_width', row.get(FACILITY_WIDTH, 3)),
        get_risk('flow_direction', row.get(FLOW_DIRECTION, 1)),
        get_risk('bicycle_speed', row.get(BICYCLE_SPEED, 1)),
        get_risk('width_restriction', row.get(WIDTH_RESTRICTION, 2)),
    ]
    cu17_product = np.prod(cu17_factors)
    return cu17_product ** (1 + cq_sum * 0.1)


def calculate_cm27(row: pd.Series) -> float:
    """CM27 'Loss of control – function' (v2.13 name: CM25)."""
    cq27_triggers = [
        get_cond('tram_rails', row.get(TRAM_RAILS, 2)),
        get_cond('surface_deformation', row.get(SURFACE_DEFORMATION, 2)),
    ]
    cq_sum = sum(cq27_triggers)
    if cq_sum == 0:
        return 0

    cu27_factors = [
        get_risk('street_lighting', row.get(STREET_LIGHTING, 1)),
        get_risk('bicycle_speed', row.get(BICYCLE_SPEED, 1)),
        get_risk('grade', row.get(GRADE, 1)),
        get_risk('facility_width', row.get(FACILITY_WIDTH, 3)),
        get_risk('flow_direction', row.get(FLOW_DIRECTION, 1)),
        get_risk('tram_rails', row.get(TRAM_RAILS, 2)),
    ]
    cu27_product = np.prod(cu27_factors)
    return cu27_product ** (1 + cq_sum * 0.1)


def calculate_cm42(row: pd.Series) -> float:
    """CM42 'Vehicle impact' (v2.13 name: CM40).

    The 'Unaccessible facility - Part 2' trigger (CQ46) evaluates in the
    workbook to the facility's own category, so it is the facility-type
    VB-conditional (DR column) — see module docstring.
    """
    facility_vb_cond = LOOKUP_TABLES['facility_type'].get(row.get(FACILITY_TYPE, 1), {}).get('vb_cond', 0)

    cq42_triggers = [
        get_cond('intersection_crossing', row.get(INTERSECTION_CROSSING, 2)),
        get_cond('property_access', row.get(PROPERTY_ACCESS, 2)),
        get_cond('adjacent_road_0_1m', row.get(ADJACENT_ROAD_0_1M, 2)),
        get_cond('adjacent_road_1_3m', row.get(ADJACENT_ROAD_1_3M, 2)),
        facility_vb_cond,
        get_cond('intersection_approach', row.get(INTERSECTION_APPROACH, 2)),
    ]
    cq_sum = sum(cq42_triggers)
    if cq_sum == 0:
        return 0

    # CU54 uses vb_cf (col DT), not vb_sev (col DS).
    # vb_sev is consumed only in the CH severity chains (BX28/34/42/47/51 below).
    facility_vb_cf = LOOKUP_TABLES['facility_type'].get(row.get(FACILITY_TYPE, 1), {}).get('vb_cf', 1.0)

    # CU52: 1.2 only when Delineation is Present AND Adjacent vehicle parking
    # 0-1m is Present (`=IF(AND(CT52=1,CT45=1),1.2,1)`).
    delineation_parking_factor = 1.2 if (
        row.get(DELINEATION, 2) == 1 and row.get(ADJACENT_PARKING_0_1M, 2) == 1
    ) else 1.0

    cu42_factors = [
        get_risk('crossing_facility', row.get(CROSSING_FACILITY, 1)),
        get_risk('line_of_sight', row.get(LINE_OF_SIGHT, 1)),
        get_risk('flow_direction', row.get(FLOW_DIRECTION, 1)),
        get_risk('adjacent_parking_0_1m', row.get(ADJACENT_PARKING_0_1M, 2)),
        get_risk('adjacent_parking_1_3m', row.get(ADJACENT_PARKING_1_3M, 2)),
        get_risk('street_lighting', row.get(STREET_LIGHTING, 1)),
        get_risk('num_lanes_adjacent', row.get(NUM_LANES_ADJACENT, 1)),
        get_risk('num_lanes_intersecting', row.get(NUM_LANES_INTERSECTING, 1)),
        get_aadt_risk_factor(float(row.get(ROAD_AADT) if row.get(ROAD_AADT) is not None else 5000)),
        get_risk('heavy_vehicle', row.get(HEAVY_VEHICLE, 1)),
        delineation_parking_factor,
        get_risk('light_segregation', row.get(LIGHT_SEGREGATION, 2)),
        facility_vb_cf,
    ]
    cu42_product = np.prod(cu42_factors)
    return cu42_product ** (1 + cq_sum * 0.1)


# Legacy v2.13 row-number aliases (kept for older parity scripts)
calculate_cm16 = calculate_cm17
calculate_cm25 = calculate_cm27
calculate_cm40 = calculate_cm42


# ============ SCORE CALCULATION ============
def calculate_cyclerap_score(row: pd.Series, cm3: float, cm17: float, cm27: float, cm42: float) -> tuple:
    """
    Calculate all risk components from CycleRAP algorithm.

    Returns tuple: (BB, BP, SB, VB, total)
    """
    # CJ values (likelihood bases)
    cj3 = cm3 + cm17
    cj27 = cm27
    cj42 = cm42

    # === BB SCORE (Bicyclist-Bicyclist) ===
    bb_severity = [
        get_risk('bicycle_speed', row.get(BICYCLE_SPEED, 1)),
        get_risk('grade', row.get(GRADE, 1)),
        get_risk('speed_differential', row.get(SPEED_DIFFERENTIAL, 1)),
        get_risk('cargo_bikes', row.get(CARGO_BIKES, 1)),
    ]
    bb_sev_product = np.prod(bb_severity)
    cd3 = cj3 * bb_sev_product
    bb = cd3

    # === BP SCORE (Bicyclist-Pedestrian) ===
    bp_sidewalk_cond = (
        get_cond('adjacent_sidewalk_0_1m', row.get(ADJACENT_SIDEWALK_0_1M, 2)) +
        get_cond('adjacent_sidewalk_1_3m', row.get(ADJACENT_SIDEWALK_1_3M, 2))
    )
    bx8 = cd3 if bp_sidewalk_cond > 0 else 0

    facility_type = row.get(FACILITY_TYPE, 1)
    bp_ped_cond = (
        get_cond('pedestrian_flow', row.get(PEDESTRIAN_FLOW, 1)) +
        LOOKUP_TABLES['facility_type'].get(facility_type, {}).get('bp_cond', 0) +
        get_cond('facility_access', row.get(FACILITY_ACCESS, 1))
    )
    bx11 = cd3 if bp_ped_cond > 0 else 0
    bp = bx8 + bx11

    # === SB SCORE (Bicyclist-Severe Hazard) ===
    sb_severity = [
        get_risk('bicycle_speed', row.get(BICYCLE_SPEED, 1)),
        get_risk('grade', row.get(GRADE, 1)),
        get_risk('adjacent_hazard_0_1m', row.get(ADJACENT_HAZARD_0_1M, 2)),
        get_risk('adjacent_hazard_1_3m', row.get(ADJACENT_HAZARD_1_3M, 2)),
    ]
    sb_sev_product = np.prod(sb_severity)

    sb_departure_cond = (
        get_cond('adjacent_object_0_1m', row.get(ADJACENT_OBJECT_0_1M, 2)) +
        get_cond('adjacent_object_1_3m', row.get(ADJACENT_OBJECT_1_3M, 2)) +
        get_cond('adjacent_hazard_0_1m', row.get(ADJACENT_HAZARD_0_1M, 2)) +
        get_cond('adjacent_hazard_1_3m', row.get(ADJACENT_HAZARD_1_3M, 2)) +
        get_cond('adjacent_parking_0_1m', row.get(ADJACENT_PARKING_0_1M, 2)) +
        get_cond('adjacent_parking_1_3m', row.get(ADJACENT_PARKING_1_3M, 2))
    )
    cd17 = cj3 * sb_sev_product
    bx17 = cd17 if sb_departure_cond > 0 else 0

    sb_fall_severity = [
        get_risk('bicycle_speed', row.get(BICYCLE_SPEED, 1)),
        get_risk('grade', row.get(GRADE, 1)),
    ]
    cd24 = (cj3 + cj27) * np.prod(sb_fall_severity)
    bx24 = cd24

    sb = bx17 + bx24

    # === VB SCORE (Vehicle-Bicyclist) ===
    # NB: must treat 0 as a real value (speed=0 maps to table factor 1.0); only
    # fall back when None/blank
    raw_speed = row.get(ROAD_SPEED, 50)
    raw_aadt = row.get(ROAD_AADT, 5000)
    raw_unit = row.get(SPEED_UNIT, 1)
    speed_unit = int(raw_unit) if raw_unit is not None else 1
    speed_risk = get_road_speed_risk_factor(
        float(raw_speed if raw_speed is not None else 50), unit=speed_unit,
    )
    aadt_risk = get_aadt_risk_factor(float(raw_aadt if raw_aadt is not None else 5000))
    facility_vb_sev = LOOKUP_TABLES['facility_type'].get(facility_type, {}).get('vb_sev', 1.0)
    facility_vb_cond = LOOKUP_TABLES['facility_type'].get(facility_type, {}).get('vb_cond', 0)

    # CH28:CH30 severity factors
    ch28_30_product = aadt_risk * speed_risk * get_risk('heavy_vehicle', row.get(HEAVY_VEHICLE, 1))

    # CH28:CH32 severity factors
    ch28_32_product = ch28_30_product * get_risk('adjacent_road_1_3m', row.get(ADJACENT_ROAD_1_3M, 2)) * facility_vb_sev

    # CH42:CH45 severity factors
    ch42_45_product = speed_risk * get_risk('heavy_vehicle', row.get(HEAVY_VEHICLE, 1)) * \
                      get_risk('adjacent_road_1_3m', row.get(ADJACENT_ROAD_1_3M, 2)) * facility_vb_sev

    # BX28: Fall/conflict with vehicle exposure
    cb28_31_sum = (
        get_cond('adjacent_road_0_1m', row.get(ADJACENT_ROAD_0_1M, 2)) +
        get_cond('intersection_crossing', row.get(INTERSECTION_CROSSING, 2)) +
        facility_vb_cond +
        get_cond('intersection_approach', row.get(INTERSECTION_APPROACH, 2))
    )
    cd28 = (cj3 + cj27) * ch28_30_product
    bx28 = cd28 if cb28_31_sum > 0 else 0

    # BX34: Departure from facility toward road
    cb34_38_sum = (
        get_cond('intersection_approach', row.get(INTERSECTION_APPROACH, 2)) +
        get_cond('adjacent_road_0_1m', row.get(ADJACENT_ROAD_0_1M, 2)) +
        get_cond('adjacent_road_1_3m', row.get(ADJACENT_ROAD_1_3M, 2)) +
        facility_vb_cond +
        get_cond('intersection_crossing', row.get(INTERSECTION_CROSSING, 2))
    )
    cd29 = cj3 * ch28_32_product
    bx34 = cd29 if cb34_38_sum > 0 else 0

    # BX42: Share space conflict
    cb42_44_sum = (
        facility_vb_cond +
        get_cond('intersection_approach', row.get(INTERSECTION_APPROACH, 2)) +
        get_cond('facility_access', row.get(FACILITY_ACCESS, 1))
    )
    cd42 = cj42 * ch42_45_product
    bx42 = cd42 / 3 if cb42_44_sum > 0 else 0

    # BX47: Vehicle deviation into facility
    cb47_49_sum = (
        get_cond('adjacent_road_0_1m', row.get(ADJACENT_ROAD_0_1M, 2)) +
        get_cond('adjacent_road_1_3m', row.get(ADJACENT_ROAD_1_3M, 2)) +
        get_cond('light_segregation', row.get(LIGHT_SEGREGATION, 2))
    )
    bx47 = cd42 / 3 if cb47_49_sum > 0 else 0

    # BX51: Intersection conflict with vehicle
    cb51_52_sum = (
        get_cond('intersection_crossing', row.get(INTERSECTION_CROSSING, 2)) +
        get_cond('property_access', row.get(PROPERTY_ACCESS, 2))
    )
    bx51 = cd42 / 3 if cb51_52_sum > 0 else 0

    vb = bx28 + bx34 + bx42 + bx47 + bx51

    # === TOTAL SCORE ===
    total = bb + bp + sb + vb

    return bb, bp, sb, vb, total


BAND_THRESHOLDS = {k: tuple(v) for k, v in _MODEL["bands"].items()}


def calculate_risk_band_for_type(score: float, crash_type: str = "VB") -> int:
    """
    Convert a risk score to a risk band category (1-4 scale) based on crash type.

    v2.14 thresholds are INCLUSIVE upper bounds (BU4/BU9/BU18/BU29):
    BB, BP, SB: <=5 Low, <=10 Medium, <=20 High, >20 Extreme
    VB (and default): <=10 Low, <=25 Medium, <=60 High, >60 Extreme
    """
    t1, t2, t3 = BAND_THRESHOLDS.get(crash_type, BAND_THRESHOLDS["VB"])
    if score <= t1:
        return 1
    elif score <= t2:
        return 2
    elif score <= t3:
        return 3
    else:
        return 4


def calculate_top_contributing_attributes(row: pd.Series, base_total_score: float) -> list:
    """
    Calculate the marginal impact (score reduction) of each attribute if set to its safest value.
    Returns the top 5 attributes that contribute most to the score.
    """
    contributions = []
    for attr, safest_val in BASELINE_VALUES.items():
        # Check if attribute exists in row
        current_val = row.get(attr)
        if pd.isna(current_val):
            continue

        # Avoid calculating if it is already the safest value
        try:
            if float(current_val) == float(safest_val):
                continue
        except (ValueError, TypeError):
            if current_val == safest_val:
                continue

        # Create a modified row
        mod_row = row.copy()
        mod_row[attr] = safest_val

        # Recalculate score
        cm3 = calculate_cm3(mod_row)
        cm17 = calculate_cm17(mod_row)
        cm27 = calculate_cm27(mod_row)
        cm42 = calculate_cm42(mod_row)
        _, _, _, _, mod_total_score = calculate_cyclerap_score(mod_row, cm3, cm17, cm27, cm42)

        reduction = float(base_total_score - mod_total_score)
        if reduction > 0.001:  # Only consider meaningful reductions
            contributions.append({
                "name": attr,
                "contribution": round(reduction, 4)
            })

    # Sort by contribution descending
    contributions.sort(key=lambda x: x["contribution"], reverse=True)
    return contributions[:5]


def calculate_cyclerap_score_native(attributes_df: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate cycleRAP scores using the v2.14 algorithm.

    Each row in the input DataFrame is scored independently.

    Args:
        attributes_df: DataFrame with 40+ coded attributes

    Returns:
        DataFrame with 10 columns:
        - BB, BB Band, BP, BP Band, SB, SB Band, VB, VB Band
        - Overall Risk Level, Overall Risk Level Band
    """
    results = []

    for idx, row in attributes_df.iterrows():
        # Calculate CM components
        cm3 = calculate_cm3(row)
        cm17 = calculate_cm17(row)
        cm27 = calculate_cm27(row)
        cm42 = calculate_cm42(row)

        # Calculate component scores
        bb_score, bp_score, sb_score, vb_score, total_score = calculate_cyclerap_score(
            row, cm3, cm17, cm27, cm42
        )

        # Calculate risk bands using specific thresholds
        bb_band = calculate_risk_band_for_type(bb_score, 'BB')
        bp_band = calculate_risk_band_for_type(bp_score, 'BP')
        sb_band = calculate_risk_band_for_type(sb_score, 'SB')
        vb_band = calculate_risk_band_for_type(vb_score, 'VB')

        # Overall Risk Level Band is now determined by the MAXIMUM band among the components
        # This aligns with the "Highest Risk Category" logic used in the frontend
        total_band = max(bb_band, bp_band, sb_band, vb_band)

        # Calculate top contributing attributes
        top_contributors = calculate_top_contributing_attributes(row, total_score)

        result_dict = {
            'BB': round(bb_score, 4),
            'BB Band': bb_band,
            'BP': round(bp_score, 4),
            'BP Band': bp_band,
            'SB': round(sb_score, 4),
            'SB Band': sb_band,
            'VB': round(vb_score, 4),
            'VB Band': vb_band,
            'Overall Risk Level': round(total_score, 4),
            'Overall Risk Level Band': total_band,
        }

        # Populate Top 1-5 Contributors
        for i in range(5):
            name_key = f'Top {i+1} Contributor'
            contrib_key = f'Top {i+1} Contribution'
            if i < len(top_contributors):
                result_dict[name_key] = top_contributors[i]["name"]
                result_dict[contrib_key] = top_contributors[i]["contribution"]
            else:
                result_dict[name_key] = None
                result_dict[contrib_key] = None

        results.append(result_dict)

    return pd.DataFrame(results)
