"""CycleRAP v2.14 STM treatment catalog and applicability engine.

The catalog is loaded from `data/stm_v214_treatments.json`, generated by
`scripts/extract_v214_model.py` from the supplier workbook's "STM" tab — do
not edit treatments by hand; re-run the extractor instead.

Semantics (STM rows 5/6/7/8/9):
  - A treatment carries one or more TRIGGER SETS. It is applicable to a
    segment if ANY set passes.
  - Within a set, every attribute group must match: the segment's coded value
    must be one of the listed categories (OR within a group, AND across
    groups).
  - A set may also carry Road AADT and/or Road operating speed RANGE bounds
    (>=, >, <, <=) which must all hold.
  - mph-variant treatments constrain "Road operating speed (unit)" to 2 in
    their trigger sets, so they are never applicable to km/h-coded data.

Missing/blank attribute values fail the trigger set (fail-closed), except the
speed unit, which defaults to 1 (km/h) to match the scoring engine.
"""

import json
import math
from pathlib import Path

import pandas as pd

from app.services.serializer import Attributes

_TREATMENTS_JSON = Path(__file__).resolve().parent / "data" / "stm_v214_treatments.json"
with open(_TREATMENTS_JSON, "r", encoding="utf-8") as _f:
    _DATA = json.load(_f)

CATALOG_VERSION = _DATA["version"]

#: All 30 v2.14 STM treatments: {id, name, unit_scope, requires_manual_value,
#: effects: {attr: value}, trigger_sets: [{attrs, aadt?, speed?}]}
TREATMENTS = _DATA["treatments"]
TREATMENT_BY_ID = {t["id"]: t for t in TREATMENTS}

SPEED_UNIT_FIELD = Attributes.Fields.SPEED_UNIT_STR
ROAD_AADT_FIELD = Attributes.Fields.ROAD_AADT_STR
ROAD_SPEED_FIELD = Attributes.Fields.ROAD_OPR_SPEED_AVG_STR

_RANGE_FIELDS = {"aadt": ROAD_AADT_FIELD, "speed": ROAD_SPEED_FIELD}


def _as_number(value):
    """Coerce a cell value to float, returning None for blanks/non-numerics."""
    if value is None:
        return None
    try:
        f = float(value)
    except (TypeError, ValueError):
        return None
    return None if math.isnan(f) else f


def _range_holds(value, bounds) -> bool:
    if value is None:
        return False
    return not (
        ("ge" in bounds and not value >= bounds["ge"])
        or ("gt" in bounds and not value > bounds["gt"])
        or ("lt" in bounds and not value < bounds["lt"])
        or ("le" in bounds and not value <= bounds["le"])
    )


def trigger_set_matches(row, trigger_set) -> bool:
    """Evaluate one trigger set against a segment's attribute row (Series or
    dict of coded values)."""
    getter = row.get if hasattr(row, "get") else lambda k, d=None: row[k] if k in row else d
    for field, cats in trigger_set.get("attrs", {}).items():
        raw = getter(field)
        value = _as_number(raw)
        if value is None and field == SPEED_UNIT_FIELD:
            value = 1.0  # default km/h, matching the scoring engine
        if value is None or int(value) not in cats:
            return False
    for key, field in _RANGE_FIELDS.items():
        bounds = trigger_set.get(key)
        if bounds and not _range_holds(_as_number(getter(field)), bounds):
            return False
    return True


def is_treatment_applicable(row, treatment) -> bool:
    """A treatment applies if ANY of its trigger sets fully matches."""
    return any(trigger_set_matches(row, ts) for ts in treatment["trigger_sets"])


def treatment_mask(attrs_df: pd.DataFrame, treatment) -> pd.Series:
    """Vectorized applicability mask over a whole attributes DataFrame."""
    mask = pd.Series(False, index=attrs_df.index)
    for trigger_set in treatment["trigger_sets"]:
        set_mask = pd.Series(True, index=attrs_df.index)
        for field, cats in trigger_set.get("attrs", {}).items():
            if field not in attrs_df.columns:
                if field == SPEED_UNIT_FIELD and 1 in cats:
                    continue  # default km/h passes
                set_mask[:] = False
                break
            col = pd.to_numeric(attrs_df[field], errors="coerce")
            if field == SPEED_UNIT_FIELD:
                col = col.fillna(1)
            set_mask &= col.isin(cats)
        else:
            for key, field in _RANGE_FIELDS.items():
                bounds = trigger_set.get(key)
                if not bounds:
                    continue
                if field not in attrs_df.columns:
                    set_mask[:] = False
                    break
                col = pd.to_numeric(attrs_df[field], errors="coerce")
                ok = col.notna()
                if "ge" in bounds:
                    ok &= col >= bounds["ge"]
                if "gt" in bounds:
                    ok &= col > bounds["gt"]
                if "lt" in bounds:
                    ok &= col < bounds["lt"]
                if "le" in bounds:
                    ok &= col <= bounds["le"]
                set_mask &= ok
        mask |= set_mask
    return mask


def applicable_treatments(row, include_manual: bool = False):
    """All catalog treatments applicable to a segment row, in catalog order.

    Treatments whose outcome requires a manually chosen value (e.g. "Vehicles
    speed control", outcome '.') are excluded unless `include_manual`."""
    return [
        t for t in TREATMENTS
        if (include_manual or not t["requires_manual_value"])
        and is_treatment_applicable(row, t)
    ]


def apply_treatment_effects(row: dict, treatment_ids) -> dict:
    """Return a copy of the attribute row with the outcome overrides of the
    given treatments applied (in the order given). Unknown IDs are ignored."""
    modified = dict(row)
    for tid in treatment_ids:
        treatment = TREATMENT_BY_ID.get(int(tid))
        if not treatment:
            continue
        for field, value in treatment["effects"].items():
            modified[field] = value
    return modified


def catalog_for_api() -> list:
    """JSON-safe catalog for the frontend `GET .../treatments/catalog`."""
    return TREATMENTS
